add 1.20.5 support
TriumphTeam/triumph-gui pull request #112
Opened 2024-04-28 12:00 UTC by iGabyTM

- changes how the MC version is detected
- uses a different ComponentSerializer on 1.20.5+ for the item and lore of the item

Paper post https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/

2024-04-28 20:30 UTC, Kqliber approved these changes

2024-05-20 09:51 UTC, Euphillya commented
Why revert Folia ?!

2024-05-20 10:48 UTC, Euphillya requested changes

2024-05-20 10:48 UTC, Euphillya commented on core/src/main/java/dev/triumphteam/gui/guis/BaseGui.java
> -
Can be replaced by a reflection:

```java
try {
    Class<?> playerClass = player.getClass();
    Method getSchedulerMethod = playerClass.getMethod("getScheduler");
    Object scheduler = getSchedulerMethod.invoke(player);
    
    Class<?> schedulerClass = scheduler.getClass();
    
    Method executeMethod = schedulerClass.getMethod("execute", Object.class, Runnable.class, Object.class, long.class);
    
    Runnable task = () -> {
        this.runCloseAction = runCloseAction;
        player.closeInventory();
        this.runCloseAction = true;
    };
    executeMethod.invoke(scheduler, plugin, task, null, 2L);
    
} catch (Exception e) {
    e.printStackTrace();
}
```

2024-05-20 18:20 UTC, LichtHund commented
> Why revert Folia ?!
Because it requires the project to be higher Java version than intended, it needs to stay on Java 8.
I was intending on doing it in a different way, the suggestion you gave is great. Ty!

2024-05-20 19:47 UTC, Euphillya commented
> > Why revert Folia ?!
> 
> Because it requires the project to be higher Java version than intended, it needs to stay on Java 8. I was intending on doing it in a different way, the suggestion you gave is great. Ty!

Alright I understand. So reflection is the best solution.

2024-05-22 17:46 UTC, Azoraqua approved these changes

2024-06-03 22:29 UTC, merged

2024-06-04 07:13 UTC, Azoraqua commented
> > Why revert Folia ?!
> 
> 
> 
> Because it requires the project to be higher Java version than intended, it needs to stay on Java 8.
> 
> I was intending on doing it in a different way, the suggestion you gave is great. Ty!

May I ask what the reason as to why it must stay on Java 8 despite most platforms, including Minecraft itself running on Java 17 by now?

2024-06-04 09:16 UTC, LichtHund commented
> May I ask what the reason as to why it must stay on Java 8 despite most platforms, including Minecraft itself running on Java 17 by now?

Because the library supports all the down to Spigot 1.8.8, there are a lot of legacy plugins depending on it and a sudden Java version change would not go well with them. This will change with v4 which will fully drop legacy support.